---
title: "Presentation of Group Homework2"
output: html_document
---

In Group homework 2, we are asked to analyze the weekly and monthly excess rentals of the bikes sharing. We need to calculate the actual and expected rentals first on a weekly and annual basis.

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
library(knitr)
```

```{r, get_tfl_data, cache=TRUE}
url <- "https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx"

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp <- tempfile(fileext = ".xlsx")))

# Use read_excel to read it as dataframe
bike0 <- read_excel(bike.temp,
                   sheet = "Data",
                   range = cell_cols("A:B"))

# change dates to get year, month, and week
bike <- bike0 %>% 
  clean_names() %>% 
  rename (bikes_hired = number_of_bicycle_hires) %>% 
  mutate (year = year(day),
          month = lubridate::month(day),
          week = isoweek(day))
glimpse(bike)
```

```{r}
# calculate the expected rentals and actual rentals
bike2 <- bike  %>%
  filter(year %in% c("2015","2016","2017","2018","2019","2020"))%>%
  group_by(year,month) %>%
  mutate(average_month=mean(bikes_hired)) %>%
  ungroup() %>%
  group_by(year,week)%>%
  mutate(average_week=mean(bikes_hired)) %>%
  ungroup()%>%
  group_by(month)%>%
  mutate(expected_month=mean(bikes_hired))%>%
  ungroup()%>%
  group_by(week)%>%
  mutate(expected_week=mean(bikes_hired)) %>%
  ungroup() %>%
  mutate(excess_month=average_month-expected_month,excess_week=average_week-expected_week)
glimpse(bike2)

# clean the data for monthly average
bikemonth <-bike2 %>%
  select(day,year,month,average_month,expected_month,excess_month) %>%
  group_by(year,month) %>%
  filter(row_number()==1)%>%
  ungroup()%>%
  mutate(excess=ifelse(excess_month<0,"A","B"),
         min=ifelse(excess_month<=0,average_month,expected_month),
         max=ifelse(excess_month>0,average_month,expected_month))
glimpse(bikemonth)
    

# draw plot of monthly change
  ggplot(bikemonth)+
    facet_wrap(vars(year))+
    geom_line(aes(x=month,y=expected_month,group=1),color="blue")+
    geom_line(aes(x=month,y=average_month,group=1))+
    geom_ribbon(aes(x=month,ymin=min,ymax=expected_month),fill="#fa9fb5",alpha=0.6)+
    geom_ribbon(aes(x=month,ymin=min,ymax=average_month),fill="#c7e9c0",alpha=0.6)+
    scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10,11,12),labels = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))+
    theme(panel.border =element_rect(color="transparent",fill="transparent"),
          panel.background=element_rect(fill="white"),
          panel.grid.major = element_line(colour = "#f0f0f0"),
          panel.grid.minor = element_line(colour = "#f0f0f0"),
          strip.background = element_rect(color="transparent",fill="transparent"),
          plot.title=element_text(size=10,face="bold"),
          plot.subtitle=element_text(size=9),
          strip.text=element_text(size=7),
          axis.text.x=element_text(size=6),
          axis.text.y=element_text(size=7),
          axis.ticks=element_blank(),
          plot.caption = element_text(size=8))+
    labs(x=NULL,y="Bike rentals",title="Monthly changes in Tfl bike rentals",subtitle = "Change from monthly average shown in blue\nand calculated between 2015-2019",caption="Source:Tfl,London Data Store")+
    guides(fill=F)+
    coord_fixed(ratio=0.0004)
```



```{r}
#clean the data of weekly rentals
bikeweek <- bike2 %>%
  select(day,year,week,average_week,expected_week,excess_week) %>%
  group_by(year,week) %>%
  filter(row_number()==1)%>%
  ungroup()%>%
  mutate(change_rate=excess_week/expected_week,group=ifelse(change_rate>0,"A","B"),rectangle=ifelse(week %in% c(14:26,40:52),"G","W"),min=ifelse(change_rate>0,0,change_rate))
glimpse(bikeweek)
 
#draw plot of weekly rentals
ggplot(bikeweek)+
  facet_wrap(vars(year))+
  geom_rect(aes(xmin=13,xmax=26,ymin=-Inf,ymax=+Inf),fill="#f0f0f0",alpha=0.1)+
  geom_rect(aes(xmin=39,xmax=52,ymin=-Inf,ymax=+Inf),fill="#f0f0f0",alpha=0.1)+
  geom_rug(aes(x=week,color=group))+
  geom_line(aes(x=week,y=change_rate,group=1))+
  geom_ribbon(aes(x=week,ymin=min,ymax=change_rate),fill="#c7e9c0",alpha=0.6)+
  geom_ribbon(aes(x=week,ymin=min,ymax=0),fill="#fa9fb5",alpha=0.6)+
  scale_y_continuous(labels=c("-60%","-30%","0%","30%","60%"),breaks=c(-0.6,-0.3,0,0.3,0.6))+
  scale_x_continuous(breaks=seq(0,53,13))+
  theme(  panel.border=element_blank(),
          axis.ticks=element_line(),
          panel.background=element_rect(fill="white"),
          panel.grid.major = element_line(colour = "#d2d2d2"),
          panel.grid.minor = element_line(colour = "#d2d2d2"),
          strip.background = element_rect(color="transparent",fill="transparent"),
          plot.title=element_text(size=10,face="bold"),
          plot.subtitle=element_text(size=9),
          strip.text=element_text(size=7),
          axis.text.x=element_text(size=7),
          axis.text.y=element_text(size=7),
          plot.caption = element_text(size=8))+
  labs(x="week",y=NULL,title="Weekly change in Tfl bike rentals",subtitle="%change from weekly averages\ncalculated between 2015-2019",caption="Source:Tfl,London Data Store")+
  guides(fill=F,color=F)+
  scale_color_manual(values=c("#c7e9c0","#fa9fb5"))
```